#!/bin/sh -e
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2013 Daniel Heule (hda at sfs.biz)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

globalopts='--quiet --non-interactive'

if test -f "${__object:?}/parameter/name"
then
    name="${__object:?}/parameter/name"
else
    name=${__object_id:?}
fi

state_should=$(cat "${__object:?}/parameter/state")
ptype=$(cat "${__object:?}/parameter/ptype")

if test -f "${__object:?}/parameter/version"
then
    version_should=$(cat "${__object:?}/parameter/version")
    if test "${ptype}" != 'package'
    then
        echo 'version support only for type package implemented' >&2
        exit 2
    fi
fi

version_is=$(cat "${__object:?}/explorer/pkg_version")
if test -n "${version_is}"
then
    state_is='present'
else
    state_is='absent'
fi


case ${state_should}
in
    (present)
        if test -z "${version_should-}"
        then
            test "${state_is}" != 'present' || exit 0

            echo "zypper ${globalopts} install --type '${ptype}' --auto-agree-with-licenses '${name}' >/dev/null"
            echo 'installed' >>"${__messages_out:?}"
        else
            [ "${state_is}" = 'present' ] && [ "${version_should}" = "${version_is}" ] && exit 0 # if state is present and version is correct, we dont need to do anything

            echo "zypper ${globalopts} install --oldpackage --type '${ptype}' --auto-agree-with-licenses '${name}' = '${version_should}' >/dev/null"
            echo 'installed' >>"${__messages_out:?}"
        fi
        ;;
    (absent)
        test "${state_is}" != 'absent' || exit 0

        echo "zypper ${globalopts} remove --type '${ptype}' '${name}' >/dev/null"
        echo 'removed' >>"${__messages_out:?}"
        ;;
    (*)
        printf 'Invalid --state: %s\n' "${state_should}" >&2
        exit 1
        ;;
esac
