#!/bin/sh
#
# 2011-2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2013 Daniel Heule (hda at sfs.biz)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the version of the package currently installed.
#

if test -f "${__object:?}/parameter/name"
then
    name=$(cat "${__object:?}/parameter/name")
else
    name=${__object_id:?}
fi

if test -f "${__object:?}/parameter/ptype"
then
    ptype=$(cat "${__object:?}/parameter/ptype")
else
    ptype='package'
fi

case ${ptype}
in
    (package)
        zypper search --details --match-exact --installed-only --type "${ptype}" "${name}" | awk -F ' *\\| *' '"i"==$1 { print $4 }'
        ;;
    # (patch|pattern|product|srcpackage)
    #     zypper search --match-exact --installed-only --type "${ptype}" "${name}" | awk -F ' *\\| *' '"i"==$1 { print $2 }'
    #     ;;
    (*)
        printf 'Invalid --ptype: %s\n' "${ptype}" >&2
        exit 1
        ;;
esac
