#!/bin/sh -e
#
# 2018 Thomas Eckert (tom at it-eckert.de)
# 2024 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the "reconstructed" package filename if the package is installed.
# Nothing, otherwise.
#

package=${__object_id:?}
package_file=${package##*/}
package_name=${package_file%%_*}

dpkg_status=$(dpkg-query --show --showformat='${db:Status-Abbrev} ${binary:Package}_${Version}_${Architecture}.deb\n' "${package_name}" 2>/dev/null || :)

case ${dpkg_status}
in
	(ii\ *)
		echo "${dpkg_status##* }"
		;;
esac
