#!/bin/sh -e
#
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the current values of the attributes set in the security file.
#

file=$(cat "${__object:?}/parameter/file")
stanza=$(cat "${__object:?}/parameter/stanza")

test -f "${file}" || exit 0

test -s "${__object:?}/parameter/attribute" || exit 0

# NOTE: we run lssec for every attribute to have cleaner output which is
#       less error-prone to split if values contain special characters (like
#       spaces or colons).
#       Thanks, IBM.
while read -r _attribute
do
	lssec -f "${file}" -s "${stanza}" -a "${_attribute%%=*}"
done <"${__object:?}/parameter/attribute" \
| awk -v stanza="${stanza}" '
  {
	  if (1 == index($0, stanza" ")) { print substr($0, length(stanza)+2) }
  }'
