#!/bin/sh -e
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#

read -r state_should <"${__object:?}/parameter/state"

case ${state_should}
in
	(present)
		__package git

		source=$(cat "${__object:?}/parameter/source")
		case ${source}
		in
			(https://*)
				os=$(cat "${__global:?}/explorer/os")
				case ${os}
				in
					(debian|devuan|ubuntu)
						__package_apt ca-certificates
						;;
				esac
				;;
		esac
		;;

	(absent)
		# let __directory handle removal of git repos
		__directory "${__object_id:?}" --state absent
		;;

	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
