#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2024 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Get an existing user's passwd entry.
#

name=${__object_id:?}

if command -v getent >/dev/null 2>&1
then
	getent passwd "${name}" || :
elif command -v dcsl >/dev/null 2>&1
then
	# Mac OS X uses Open Directory to manage users and groups.
	# /etc/passwd is only used in single-user mode.
	dscl -q . -read "/Users/${name}" | awk -F ':( +|$)' '
	/^ / {
		sub(/^ */, "")
		e[e_last] = e[e_last] $0
		next
	}
	$2 {
		e[$1] = $2
		e_last = $1
	}

	END {
		sub("^\*+$/", "*", e["Password"])

		printf "%s:%s:%u:%u:%s:%s:%s"ORS
			e["RecordName"],
			e["Password"],
			e["UniqueID"],
			e["PrimaryGroupID"],
			e["RealName"],
			e["NFSHomeDirectory"],
			e["UserShell"]
	}'
elif test -s /etc/passwd
then
	awk -F: -v n="${name}" 'n==$1' /etc/passwd
fi
