#!/bin/sh
#
# 2010-2011 Andi Brönnimann (andi-cdist at v-net.ch)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the processor architecture of the target.
#

command -v uname >/dev/null 2>&1 || exit 0

case $(uname -s)
in
	(AIX)
		# NOTE: AIX uses -m for machine ID. The -p option displays the processor
		#       architecture. In reality probably always "powerpc".
		#       Unfortunately, this does not allow to differentiate 64-bit
		#       systems, so we patch a 64 to the end if KERNEL_BITMODE is set to
		#       64. There is also HARDWARE_BITMODE, but I think the kernel
		#       bitness is more relevant to our use case (could we run 64-bit
		#       software on a 64-bit CPU running 32-bit AIX? IDK).
		proc=$(uname -p)
		bitmode=$(getconf KERNEL_BITMODE)

		case ${proc}@${bitmode}
		in
			(*64*@64)
				echo "${proc}" ;;
			(*@64)
				echo "${proc}64" ;;
			(*)
				echo "${proc}" ;;
		esac
		;;
	(*)
		uname -m
		;;
esac
