#!/bin/sh
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the runlevel the target is currently running in.
#

if command -v runlevel >/dev/null 2>&1
then
	runlevel | cut -d ' ' -f 2
elif test -r /var/run/runlevel
then
	cat /var/run/runlevel
elif test -r /etc/.init.state
then
	# AIX
	cat /etc/.init.state
fi
