#!/bin/sh -e
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2019,2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-base.
#
# skonfig-base is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-base is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the path of the destination file chosen to be managed.
#

if test -f "${__object:?}/parameter/file"
then
	cat "${__object:?}/parameter/file"
else
	if test -s "${__object:?}/parameter/owner"
	then
		owner=$(cat "${__object:?}/parameter/owner")
	else
		owner=${__object_id:?}
	fi

	if command -v getent >/dev/null 2>&1
	then
		owner_line=$(getent passwd "${owner}") || exit 0
	elif test -f /etc/passwd
	then
		case ${owner}
		in
			([0-9][0-9]*)
				owner_line=$(awk -v u="${owner}" -F: '$3 == u' /etc/passwd)
				;;
			(*)
				owner_line=$(awk -v u="${owner}" -F: '$1 == u' /etc/passwd)
				;;
		esac
	fi

	if test -n "${owner_line}"
	then
		home=$(printf '%s\n' "${owner_line}" | cut -d':' -f6)
	else
		# user does not exist
		exit 0
	fi

	if test ! -d "${home}"
	then
		# don't know how to determine user's home directory, fall back to ~
		home=~${owner}
		command -v realpath >/dev/null 2>&1 && home=$(realpath "${home}")
	fi

	if test -d "${home}"
	then
		printf '%s/.ssh/authorized_keys\n' "${home}"
	fi
fi
